revert

diff --git a/.pipelines/templates/deploy-stage.yml b/.pipelines/templates/deploy-stage.yml
--- a/.pipelines/templates/deploy-stage.yml
+++ b/.pipelines/templates/deploy-stage.yml
@@ -85,8 +85,7 @@ jobs:
                 scriptType: bash
                 scriptLocation: inlineScript
                 inlineScript: |
-                    set -eux  # fail on error
-                    echo IMAGE_REDACTOR_DEV_APP_NAME=$(IMAGE_REDACTOR_DEV_APP_NAME)
+                    set -eux  # fail on error                   
                     az webapp deployment slot create --name ${{ parameters.IMAGE_REDACTOR_APP_NAME }} --resource-group ${{ parameters.RESOURCE_GROUP_NAME }} --configuration-source ${{ parameters.IMAGE_REDACTOR_APP_NAME }} --slot staging
                     URI=https://$(az webapp config hostname list --webapp-name ${{ parameters.IMAGE_REDACTOR_APP_NAME }} --resource-group ${{ parameters.RESOURCE_GROUP_NAME }} --slot staging --query '[0].name' -o tsv)
                     echo $URI
