remove set -x from setvariable tasks (#863)
* remove set -x from setvariables tasks

* Update requirements-docs.txt

Co-authored-by: sharon <sharon.hart@microsoft.com>

diff --git a/.pipelines/templates/release.yml b/.pipelines/templates/release.yml
--- a/.pipelines/templates/release.yml
+++ b/.pipelines/templates/release.yml
@@ -13,7 +13,7 @@ stages:
       displayName: 'Get the version number'
       steps:
         - bash: |
-            set -eux  # exit on error
+            set -eu  # exit on error
             ver=$(cat VERSION)
             echo $ver
             echo "##vso[task.setvariable variable=version;isOutput=true]$ver"
@@ -24,7 +24,7 @@ stages:
       displayName: 'Get image-redactor version number'
       steps:
         - bash: |
-            set -eux  # exit on error
+            set -eu  # exit on error
             imageVer=$(cat VERSION-IMAGE-REDACTOR)
             echo $imageVer
             echo "##vso[task.setvariable variable=imageVersion;isOutput=true]$imageVer"
@@ -37,7 +37,7 @@ stages:
       continueOnError: true
       dependsOn: version
       variables:
-        version: $[ dependencies.Version.outputs['setVer.version'] ]
+        version: $[ dependencies.version.outputs['setVer.version'] ]
       steps:
         - task: GitHubRelease@0
           inputs:
