validate version

diff --git a/.pipelines/validate-version.yml b/.pipelines/validate-version.yml
--- a/.pipelines/validate-version.yml
+++ b/.pipelines/validate-version.yml
@@ -9,15 +9,19 @@ steps:
   inputs:
       targetType: 'inline'
       script: |
-        set -x  # log everything
+        set -eux  # exit on error
     
         GIT_DIFF_UPSTREAMBRANCH=${{ parameters.UPSTREAM_BRANCH }}
+        if [[ ! $GIT_DIFF_UPSTREAMBRANCH == *"/"* ]]; then
+          echo "missing full path, adding remotes/origin/"
+          GIT_DIFF_UPSTREAMBRANCH=remotes/origin/$GIT_DIFF_UPSTREAMBRANCH
+        fi
+
         GIT_DIFF_SOURCEBRANCH="HEAD"
 
         VERSION_FILECHANGE_SET=$(git diff "$GIT_DIFF_SOURCEBRANCH" "$GIT_DIFF_UPSTREAMBRANCH" --name-only | grep -w LICENSE)
         # check if file was changeds
         if [ -z "$VERSION_FILECHANGE_SET" ]; then
             echo "version file not changed"
-            ##vso[task.complete result=Failed;]DONE
         fi
         echo "version file changed"
